### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by francescoagati** [justinweiss/reactive_resource#1]
require 'rubygems'
require 'reactive_resource'

class ReactiveResource::Base
  self.site = "http://localhost:3000/"
  self.prefix = "/store/"
  self.format = :json
end

class ReactiveResource::Customer < ReactiveResource::Base
  has_many :addresses
end

class ReactiveResource::Address < ReactiveResource::Base
  belongs_to :customer
end

p ReactiveResource::Customer.find(2).addresses.first

call Started GET "/store/addresses.json" for 127.0.0.1 at Tue Jan 25 18:18:09 +0100 2011

ActionController::RoutingError (No route matches "/store/addresses.json"):
 instead of store/customers/2/addresses

**Comment by justinweiss** [comment]
Hm, I'm not sure what's going on here. Does it do the initial request for /store/customers/2.html before it fails? I'm guessing somehow the belongs_to on Address isn't doing the right thing, but I haven't been able to trigger this problem here yet. Can you show me the results of `ReactiveResource::Address.associations` and `ReactiveResource::Address.assocaitons.first.associated_class`? I think that would help me figure out where the problem is.

**Comment by justinweiss** [comment]
I can't really fix this without any additional information.
